//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentAdministration.UI.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StudentAdministration.UI.Resources.Languages.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note hinzufügen.
        /// </summary>
        public static string AddGradeTitle {
            get {
                return ResourceManager.GetString("AddGradeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student hinzufügen.
        /// </summary>
        public static string AddStudentTitle {
            get {
                return ResourceManager.GetString("AddStudentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anwenden.
        /// </summary>
        public static string ApplyTitle {
            get {
                return ResourceManager.GetString("ApplyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbrechen.
        /// </summary>
        public static string CancleTitle {
            get {
                return ResourceManager.GetString("CancleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Löschen.
        /// </summary>
        public static string ClearFilterTitle {
            get {
                return ResourceManager.GetString("ClearFilterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schließen.
        /// </summary>
        public static string CloseTitle {
            get {
                return ResourceManager.GetString("CloseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzahl.
        /// </summary>
        public static string CountTitle {
            get {
                return ResourceManager.GetString("CountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte verwende einen validen Kurs.
        /// </summary>
        public static string CourseErrorTitle {
            get {
                return ResourceManager.GetString("CourseErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurs.
        /// </summary>
        public static string CourseTitle {
            get {
                return ResourceManager.GetString("CourseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits.
        /// </summary>
        public static string CreditsTitle {
            get {
                return ResourceManager.GetString("CreditsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studiengang.
        /// </summary>
        public static string DegreeProgramTitle {
            get {
                return ResourceManager.GetString("DegreeProgramTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Löschen.
        /// </summary>
        public static string DeleteTitle {
            get {
                return ResourceManager.GetString("DeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string DetailsTitle {
            get {
                return ResourceManager.GetString("DetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearbeiten.
        /// </summary>
        public static string EditTitle {
            get {
                return ResourceManager.GetString("EditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        public static string EmailTitle {
            get {
                return ResourceManager.GetString("EmailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fülle alle Felder.
        /// </summary>
        public static string FillFieldsTitle {
            get {
                return ResourceManager.GetString("FillFieldsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bei dem Filtern der Studenten ist etwas schief gelaufen. Bitte versuchen sie es erneut.
        /// </summary>
        public static string FilterErrorMessage {
            get {
                return ResourceManager.GetString("FilterErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string FilterTitle {
            get {
                return ResourceManager.GetString("FilterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorname.
        /// </summary>
        public static string FirstNameTitle {
            get {
                return ResourceManager.GetString("FirstNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: {0}, {1}.
        /// </summary>
        public static string FullNameTitle {
            get {
                return ResourceManager.GetString("FullNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etwas ist schief gelaufen. Versuchen sie es bitte erneut.
        /// </summary>
        public static string GeneralErrorMessage {
            get {
                return ResourceManager.GetString("GeneralErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notendurchschnitt:.
        /// </summary>
        public static string GradeAverageTitle {
            get {
                return ResourceManager.GetString("GradeAverageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte verwende eine valide Note..
        /// </summary>
        public static string GradeErrorTitle {
            get {
                return ResourceManager.GetString("GradeErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string GradeTitle {
            get {
                return ResourceManager.GetString("GradeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bei dem Laden der Objekte ist etwas schief gelaufen. Bitte versuchen sie es erneut.
        /// </summary>
        public static string ItemLoadError {
            get {
                return ResourceManager.GetString("ItemLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nachname.
        /// </summary>
        public static string LastNameTitle {
            get {
                return ResourceManager.GetString("LastNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NameTitle {
            get {
                return ResourceManager.GetString("NameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bei dem verlassen der Seite ist etwas schief gelaufen. Versuchen sie es bitte erneut.
        /// </summary>
        public static string NavigationErrorMessage {
            get {
                return ResourceManager.GetString("NavigationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine Ergebnisse.
        /// </summary>
        public static string NoResultsTitle {
            get {
                return ResourceManager.GetString("NoResultsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine Studenten gefunden.
        /// </summary>
        public static string NoStudentsFoundTitle {
            get {
                return ResourceManager.GetString("NoStudentsFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string OkayTitle {
            get {
                return ResourceManager.GetString("OkayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string OkTitle {
            get {
                return ResourceManager.GetString("OkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bei dem Speichern ist etwas Fehlgelaufen. Bitte Versuchen sie es erneut.
        /// </summary>
        public static string SaveErrorMessage {
            get {
                return ResourceManager.GetString("SaveErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern.
        /// </summary>
        public static string SaveTitle {
            get {
                return ResourceManager.GetString("SaveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studiengang auswählen.
        /// </summary>
        public static string SelectDegreeProgramTitle {
            get {
                return ResourceManager.GetString("SelectDegreeProgramTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Student konnte nicht gelöscht werden. Bitte versuchen Sie es erneut..
        /// </summary>
        public static string StudentFailedToDeleteMessage {
            get {
                return ResourceManager.GetString("StudentFailedToDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student wurde nicht gefunden.
        /// </summary>
        public static string StudentNotFoundMessage {
            get {
                return ResourceManager.GetString("StudentNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string StudentNumberTitle {
            get {
                return ResourceManager.GetString("StudentNumberTitle", resourceCulture);
            }
        }
    }
}
